import { useMemo } from "react";
import { ArrowRight, Home, UsersRound } from "lucide-react";
import { Link } from "wouter";
import { useGetDashboardSummary, useGetVillages } from "@workspace/api-client-react";
import { DashboardShell, EmptyState, ErrorState, LoadingState, PageIntro, StatusPill, formatNumber } from "@/components/dashboard-shell";

const zones = ["Red", "Orange", "Yellow", "Green"];
const zoneColor: Record<string, string> = { Red: "#b65343", Orange: "#cb7339", Yellow: "#d5a938", Green: "#4c806d" };

export default function PopulationRisk() {
  const summaryQuery = useGetDashboardSummary();
  const villagesQuery = useGetVillages();
  const villages = useMemo(() => villagesQuery.data ?? [], [villagesQuery.data]);
  if (summaryQuery.isLoading || villagesQuery.isLoading) return <DashboardShell><LoadingState label="Calculating population exposure" /></DashboardShell>;
  if (summaryQuery.isError || villagesQuery.isError || !summaryQuery.data) return <DashboardShell><ErrorState onRetry={() => { void summaryQuery.refetch(); void villagesQuery.refetch(); }} label="Population exposure could not be loaded." /></DashboardShell>;
  const summary = summaryQuery.data;
  const zoneStats = useMemo(() => zones.map((zone) => { const inZone = villages.filter((village) => village.zone_color === zone); return { zone, population: inZone.reduce((total, village) => total + village.population, 0), households: inZone.reduce((total, village) => total + village.households, 0), villages: inZone.length }; }), [villages]);
  const exposedShare = summary.total_population ? (summary.population_at_risk / summary.total_population) * 100 : 0;
  return <DashboardShell><PageIntro eyebrow="Population desk · human impact" title="Population at risk" description="Translate hazard exposure into households and people so operational planning starts with community scale, not only geography." action={<StatusPill value={`${exposedShare.toFixed(1)}% exposed`} tone="orange" />} />
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div className="border border-[#e0b8ad] bg-[#f8e9e4] p-5"><UsersRound size={18} className="text-[#b65343]" /><p className="mt-4 font-mono text-[10px] uppercase tracking-[.14em] text-[#b65343]">People at risk</p><p className="mt-2 text-3xl font-bold text-[#984636]">{formatNumber(summary.population_at_risk)}</p></div><div className="border border-[#d7d1c5] bg-[#fbf9f3] p-5"><Home size={18} className="text-[#3f7069]" /><p className="mt-4 font-mono text-[10px] uppercase tracking-[.14em] text-[#60717c]">Households mapped</p><p className="mt-2 text-3xl font-bold">{formatNumber(summary.total_households)}</p></div><div className="border border-[#d7d1c5] bg-[#fbf9f3] p-5"><p className="font-mono text-[10px] uppercase tracking-[.14em] text-[#60717c]">Total population</p><p className="mt-4 text-3xl font-bold">{formatNumber(summary.total_population)}</p><p className="mt-1 text-xs text-[#60717c]">Across {summary.total_villages} villages</p></div><div className="border border-[#d7d1c5] bg-[#fbf9f3] p-5"><p className="font-mono text-[10px] uppercase tracking-[.14em] text-[#60717c]">Average household</p><p className="mt-4 text-3xl font-bold">{summary.total_households ? (summary.total_population / summary.total_households).toFixed(1) : "—"}</p><p className="mt-1 text-xs text-[#60717c]">People per household</p></div></section>
    <section className="mt-5 border border-[#d7d1c5] bg-[#fbf9f3]"><div className="border-b border-[#e3ded4] p-5"><p className="font-mono text-[10px] uppercase tracking-[.14em] text-[#60717c]">Impact by hazard zone</p><h2 className="mt-1 text-lg font-bold">Where people are exposed</h2></div>{villages.length ? <div className="grid divide-y divide-[#e3ded4] md:grid-cols-2 md:divide-x md:divide-y-0">{zoneStats.map(({ zone, population, households, villages: count }) => <div key={zone} className="p-5"><div className="flex items-center justify-between"><span className="flex items-center gap-2 text-sm font-bold"><span className="h-2.5 w-2.5 rounded-full" style={{ background: zoneColor[zone] }} />{zone} zone</span><span className="font-mono text-[10px] text-[#60717c]">{count} villages</span></div><p className="mt-6 font-mono text-2xl font-bold">{formatNumber(population)}</p><p className="text-xs text-[#60717c]">people · {formatNumber(households)} households</p><div className="mt-4 h-2 bg-[#e2ded3]"><div className="h-full" style={{ width: `${summary.population_at_risk ? Math.min(100, (population / summary.population_at_risk) * 100) : 0}%`, background: zoneColor[zone] }} /></div></div>)}</div> : <EmptyState title="No population records available" description="The village layer returned no population records for this view." />}</section>
    <section className="mt-5 flex items-center justify-between border border-[#d7d1c5] bg-[#f7f3ea] p-5"><div><p className="font-mono text-[10px] uppercase tracking-[.14em] text-[#60717c]">Next decision</p><p className="mt-1 text-sm font-semibold">See which villages carry the largest immediate population impact.</p></div><Link href="/relocation-priority" className="inline-flex items-center gap-2 text-xs font-bold text-[#3f7069] hover:text-[#b65343]" data-testid="link-population-priority">Open urgency queue <ArrowRight size={14} /></Link></section>
  </DashboardShell>;
}
