import { ArrowRight, ListOrdered, Route } from "lucide-react";
import { Link } from "wouter";
import { useGetPriority } from "@workspace/api-client-react";
import { DashboardShell, EmptyState, ErrorState, LoadingState, PageIntro, StatusPill, formatNumber } from "@/components/dashboard-shell";

const bucketTone: Record<string, "red" | "orange" | "yellow" | "green"> = { Immediate: "red", "Short-term": "orange", "Medium-term": "yellow", Monitor: "green" };

export default function RelocationPriority() {
  const query = useGetPriority();
  if (query.isLoading) return <DashboardShell><LoadingState label="Loading ranked urgency queue" /></DashboardShell>;
  if (query.isError) return <DashboardShell><ErrorState onRetry={() => query.refetch()} label="The urgency queue could not be loaded." /></DashboardShell>;
  const villages = query.data ?? [];
  return <DashboardShell><PageIntro eyebrow="Action queue · relocation urgency" title="Relocation priority" description="A ranked queue for deciding where to begin. Open any village to see the factors behind its position and available site matches." action={<StatusPill value={`${villages.length} ranked`} tone="green" />} />
    <section className="mb-5 grid gap-3 sm:grid-cols-3"><div className="border border-[#e0b8ad] bg-[#f8e9e4] p-5"><p className="font-mono text-[10px] uppercase tracking-[.13em] text-[#b65343]">Immediate</p><p className="mt-2 text-3xl font-bold text-[#984636]">{villages.filter((village) => village.priority_bucket === "Immediate").length}</p></div><div className="border border-[#ead0b6] bg-[#fbefe1] p-5"><p className="font-mono text-[10px] uppercase tracking-[.13em] text-[#a55b28]">Short-term</p><p className="mt-2 text-3xl font-bold text-[#a55b28]">{villages.filter((village) => village.priority_bucket === "Short-term").length}</p></div><div className="border border-[#d7d1c5] bg-[#fbf9f3] p-5"><p className="font-mono text-[10px] uppercase tracking-[.13em] text-[#60717c]">Queue scope</p><p className="mt-2 text-3xl font-bold">{formatNumber(villages.length)}</p></div></section>
    {villages.length === 0 ? <EmptyState title="The urgency queue is empty" description="No scored village records are available to rank at the moment." /> : <section className="border border-[#d7d1c5] bg-[#fbf9f3]"><div className="flex items-center gap-3 border-b border-[#e3ded4] px-5 py-4"><ListOrdered size={18} className="text-[#b65343]" /><div><p className="font-mono text-[10px] uppercase tracking-[.13em] text-[#60717c]">Ordered by priority score</p><h2 className="mt-1 text-base font-bold">Decision queue</h2></div></div><div className="divide-y divide-[#e3ded4]">{villages.map((village, index) => <div key={village.village_id} className="flex flex-col gap-4 px-5 py-5 md:flex-row md:items-center" data-testid={`row-priority-${village.village_id}`}><span className="w-8 font-mono text-lg font-bold text-[#8a989a]">{String(index + 1).padStart(2, "0")}</span><div className="min-w-0 flex-1"><Link href={`/villages/${village.village_id}`} className="text-base font-bold hover:text-[#b65343]" data-testid={`link-priority-record-${village.village_id}`}>{village.village_name}</Link><div className="mt-1 flex flex-wrap items-center gap-3 text-xs text-[#60717c]"><StatusPill value={village.priority_bucket} tone={bucketTone[village.priority_bucket] ?? "green"} /><span>{formatNumber(village.population)} residents</span><span>{village.historical_incidents} incidents</span></div></div><div className="flex items-center justify-between gap-5 md:justify-end"><div className="text-left md:text-right"><p className="font-mono text-[9px] uppercase tracking-[.1em] text-[#60717c]">Priority score</p><p className="font-mono text-xl font-bold">{village.priority_score.toFixed(1)}</p></div><Link href={`/relocation/${village.village_id}`} className="inline-flex items-center gap-2 border border-[#d7d1c5] px-3 py-2 text-xs font-bold text-[#3f7069] hover:border-[#3f7069]" data-testid={`link-relocate-${village.village_id}`}><Route size={14} />Review sites <ArrowRight size={13} /></Link></div></div>)}</div></section>}
  </DashboardShell>;
}
