import { FileText, Printer, ShieldCheck } from "lucide-react";
import { useGetDashboardSummary, useGetFacilities, useGetPriority } from "@workspace/api-client-react";
import { DashboardShell, EmptyState, ErrorState, LoadingState, PageIntro, StatusPill, formatNumber } from "@/components/dashboard-shell";

export default function Reports() {
  const summaryQuery = useGetDashboardSummary();
  const priorityQuery = useGetPriority();
  const facilitiesQuery = useGetFacilities();
  if (summaryQuery.isLoading || priorityQuery.isLoading || facilitiesQuery.isLoading) return <DashboardShell><LoadingState label="Preparing regional report" /></DashboardShell>;
  if (summaryQuery.isError || priorityQuery.isError || facilitiesQuery.isError || !summaryQuery.data) return <DashboardShell><ErrorState onRetry={() => { void summaryQuery.refetch(); void priorityQuery.refetch(); void facilitiesQuery.refetch(); }} label="The regional report could not be prepared." /></DashboardShell>;
  const summary = summaryQuery.data;
  const priorities = priorityQuery.data ?? [];
  const facilities = facilitiesQuery.data ?? [];
  const immediate = priorities.filter((village) => village.priority_bucket === "Immediate");
  return <DashboardShell><div className="print-report"><PageIntro eyebrow="Report desk · regional summary" title="Regional situation report" description="A print-friendly briefing sheet for district review across Rudraprayag and Chamoli." action={<button type="button" onClick={() => window.print()} className="inline-flex items-center gap-2 border border-[#263440] bg-[#263440] px-4 py-3 text-xs font-bold text-[#f2eee4] hover:bg-[#3f7069]" data-testid="button-print-report"><Printer size={15} />Print report</button>} />
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div className="border border-[#d7d1c5] bg-[#fbf9f3] p-5"><p className="font-mono text-[10px] uppercase tracking-[.13em] text-[#60717c]">Region</p><p className="mt-3 text-xl font-bold">{summary.region}</p><p className="mt-1 text-xs text-[#60717c]">Situation report / current layer</p></div><div className="border border-[#e0b8ad] bg-[#f8e9e4] p-5"><p className="font-mono text-[10px] uppercase tracking-[.13em] text-[#b65343]">Population at risk</p><p className="mt-3 text-3xl font-bold text-[#984636]">{formatNumber(summary.population_at_risk)}</p></div><div className="border border-[#d7d1c5] bg-[#fbf9f3] p-5"><p className="font-mono text-[10px] uppercase tracking-[.13em] text-[#60717c]">Immediate queue</p><p className="mt-3 text-3xl font-bold">{formatNumber(summary.immediate_priority)}</p></div><div className="border border-[#d7d1c5] bg-[#fbf9f3] p-5"><p className="font-mono text-[10px] uppercase tracking-[.13em] text-[#60717c]">Facilities mapped</p><p className="mt-3 text-3xl font-bold">{formatNumber(facilities.length)}</p></div></section>
    <section className="mt-5 grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><div className="border border-[#d7d1c5] bg-[#fbf9f3]"><div className="flex items-center gap-3 border-b border-[#e3ded4] p-5"><span className="grid h-8 w-8 place-items-center bg-[#e0ebe7] text-[#3f7069]"><FileText size={16} /></span><div><p className="font-mono text-[10px] uppercase tracking-[.13em] text-[#60717c]">Action summary</p><h2 className="mt-1 text-lg font-bold">Villages requiring attention</h2></div></div>{immediate.length ? <div className="divide-y divide-[#e3ded4]">{immediate.map((village) => <div key={village.village_id} className="flex items-center justify-between gap-4 p-4" data-testid={`row-report-immediate-${village.village_id}`}><div><p className="text-sm font-bold">{village.village_name}</p><p className="mt-1 text-xs text-[#60717c]">{formatNumber(village.population)} residents · {village.historical_incidents} incidents</p></div><div className="text-right"><StatusPill value={village.zone_color} tone={village.zone_color === "Red" ? "red" : village.zone_color === "Orange" ? "orange" : "yellow"} /><p className="mt-1 font-mono text-[10px] text-[#60717c]">Score {village.priority_score.toFixed(1)}</p></div></div>)}</div> : <div className="p-5"><EmptyState title="No immediate villages in queue" description="The current priority layer has no villages in the immediate bucket." /></div>}</div><div className="border border-[#d7d1c5] bg-[#3f7069] p-6 text-[#f2eee4]"><ShieldCheck size={20} className="text-[#e8b84c]" /><p className="mt-7 font-mono text-[10px] uppercase tracking-[.16em] text-[#c2d6cd]">Briefing note</p><h2 className="mt-2 text-xl font-bold">The recommendation remains accountable.</h2><p className="mt-4 text-sm leading-6 text-[#d5e2dc]">Use this report as a shared starting point. Scores show the evidence; district officers and communities make the decision.</p><div className="mt-7 border-t border-[#6f958d] pt-4 font-mono text-[10px] uppercase tracking-[.11em] text-[#c2d6cd]">Prepared from live regional data</div></div></section>
    <section className="mt-5 border border-[#d7d1c5] bg-[#f7f3ea] p-5"><p className="font-mono text-[10px] uppercase tracking-[.13em] text-[#60717c]">Report metadata</p><div className="mt-4 grid gap-4 text-xs text-[#60717c] sm:grid-cols-3"><div><span className="block font-mono text-[9px] uppercase text-[#8a989a]">Villages tracked</span><b className="mt-1 block text-[#263440]">{formatNumber(summary.total_villages)}</b></div><div><span className="block font-mono text-[9px] uppercase text-[#8a989a]">Households tracked</span><b className="mt-1 block text-[#263440]">{formatNumber(summary.total_households)}</b></div><div><span className="block font-mono text-[9px] uppercase text-[#8a989a]">Facilities reference</span><b className="mt-1 block text-[#263440]">{facilities.length} locations</b></div></div></section></div></DashboardShell>;
}
