import { useMemo, useState } from "react";
import { Link } from "wouter";
import { ArrowUpRight, Search, SlidersHorizontal } from "lucide-react";
import { useGetVillages, type GetVillagesParams } from "@workspace/api-client-react";
import { DashboardShell, EmptyState, ErrorState, LoadingState, PageIntro, StatusPill, formatNumber } from "@/components/dashboard-shell";

const zones = ["All zones", "Red", "Orange", "Yellow", "Green"];
const priorities = ["All priorities", "Immediate", "Short-term", "Medium-term", "Monitor"];
const zoneTone: Record<string, "red" | "orange" | "yellow" | "green"> = { Red: "red", Orange: "orange", Yellow: "yellow", Green: "green" };

export default function Villages() {
  const [search, setSearch] = useState("");
  const [zone, setZone] = useState("All zones");
  const [priority, setPriority] = useState("All priorities");
  const queryParams = useMemo<GetVillagesParams>(() => ({ search: search || undefined, zone: zone === "All zones" ? undefined : zone as GetVillagesParams["zone"], priority: priority === "All priorities" ? undefined : priority as GetVillagesParams["priority"] }), [search, zone, priority]);
  const query = useGetVillages(queryParams);
  if (query.isLoading) return <DashboardShell><LoadingState label="Reading village priority list" /></DashboardShell>;
  if (query.isError) return <DashboardShell><ErrorState onRetry={() => query.refetch()} /></DashboardShell>;
  const villages = query.data ?? [];
  return <DashboardShell><PageIntro eyebrow="Village register · scored view" title="Priority villages" description="Search the register, then open a village record to see the evidence behind its priority score." action={<div className="font-mono text-[10px] uppercase tracking-[.14em] text-[#60717c]">{villages.length} records returned</div>} />
    <section className="border border-[#d7d1c5] bg-[#fbf9f3]">
      <div className="flex flex-col gap-3 border-b border-[#e3ded4] p-4 lg:flex-row"><label className="relative flex-1"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#8a989a]" /><input type="search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by village name" className="h-10 w-full border border-[#d7d1c5] bg-[#f2eee4] pl-10 pr-3 text-sm outline-none placeholder:text-[#8a989a] focus:border-[#3f7069]" data-testid="input-search-villages" /></label><div className="flex items-center gap-2 text-[#60717c]"><SlidersHorizontal size={15} /><span className="hidden text-xs sm:block">Filter</span></div><select value={zone} onChange={(event) => setZone(event.target.value)} className="h-10 border border-[#d7d1c5] bg-[#f2eee4] px-3 text-sm outline-none focus:border-[#3f7069]" aria-label="Filter by hazard zone" data-testid="select-zone"><option>{zones[0]}</option>{zones.slice(1).map((item) => <option key={item}>{item}</option>)}</select><select value={priority} onChange={(event) => setPriority(event.target.value)} className="h-10 border border-[#d7d1c5] bg-[#f2eee4] px-3 text-sm outline-none focus:border-[#3f7069]" aria-label="Filter by priority" data-testid="select-priority"><option>{priorities[0]}</option>{priorities.slice(1).map((item) => <option key={item}>{item}</option>)}</select></div>
      {villages.length === 0 ? <EmptyState title="No villages match those filters" description="Try a wider search or remove one of the filters to see more of the register." /> : <div className="overflow-x-auto"><table className="w-full min-w-[760px] border-collapse text-left"><thead><tr className="border-b border-[#e3ded4] bg-[#f2eee4] font-mono text-[10px] uppercase tracking-[.12em] text-[#60717c]"><th className="px-5 py-3 font-normal">Village</th><th className="px-3 py-3 font-normal">Hazard zone</th><th className="px-3 py-3 font-normal">Population</th><th className="px-3 py-3 font-normal">Incidents</th><th className="px-3 py-3 font-normal">Priority score</th><th className="px-5 py-3 text-right font-normal">Record</th></tr></thead><tbody>{villages.map((village) => <tr key={village.village_id} className="group border-b border-[#e8e3da] last:border-0 hover:bg-[#f7f3ea]" data-testid={`row-village-${village.village_id}`}><td className="px-5 py-4"><Link href={`/villages/${village.village_id}`} className="flex items-center gap-3" data-testid={`link-village-${village.village_id}`}><span className="grid h-8 w-8 place-items-center rounded-full bg-[#e4e1d8] font-bold text-[#3f7069]">{village.village_name.slice(0, 1)}</span><span><span className="block text-sm font-bold group-hover:text-[#b65343]">{village.village_name}</span><span className="font-mono text-[9px] text-[#8a989a]">{village.lat.toFixed(3)}°N / {village.lon.toFixed(3)}°E</span></span></Link></td><td className="px-3 py-4"><StatusPill value={village.zone_color} tone={zoneTone[village.zone_color]} /></td><td className="px-3 py-4 font-mono text-sm">{formatNumber(village.population)}</td><td className="px-3 py-4 font-mono text-sm">{village.historical_incidents}</td><td className="px-3 py-4"><span className="font-mono text-sm font-bold">{village.priority_score.toFixed(1)}</span><span className="ml-2 text-xs text-[#60717c]">{village.priority_bucket}</span></td><td className="px-5 py-4 text-right"><Link href={`/villages/${village.village_id}`} className="inline-grid h-8 w-8 place-items-center border border-[#d7d1c5] text-[#60717c] hover:border-[#b65343] hover:text-[#b65343]" aria-label={`Open ${village.village_name}`} data-testid={`link-open-village-${village.village_id}`}><ArrowUpRight size={15} /></Link></td></tr>)}</tbody></table></div>}
    </section>
  </DashboardShell>;
}
